name: Frontend CI/CD

on:
  push:
    branches:
      - main

env:
  # Reusable variables
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: your-dockerhub-username/frontend
  IMAGE_TAG: ${{ github.run_id }}
  DEPLOYMENT_FILE_PATH: k8s/deployment.yaml
  CONTAINER_NAME_IN_YAML: frontend
  NODE_VERSION: '20'

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  scan-vulnerabilities:
    name: Scan Vulnerabilities
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./src/frontend

  docker-build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: scan-vulnerabilities
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG -t $DOCKER_IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
          docker push $DOCKER_IMAGE_NAME:latest

  update-k8s-manifest:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq
        run: sudo apk add yq || sudo apt-get install -y yq

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Update image tag in manifest
        run: |
          yq e "(.spec.template.spec.containers[] | select(.name == \"$CONTAINER_NAME_IN_YAML\") .image) = \"$DOCKER_IMAGE_NAME:$IMAGE_TAG\"" -i "$DEPLOYMENT_FILE_PATH"

      - name: Commit and push changes
        run: |
          git add "$DEPLOYMENT_FILE_PATH"
          git commit -m "CI: Update image tag to $IMAGE_TAG"
          git push
